const { Router } = require("express");
const route = Router();
const cntDev = require("../Controller/developer");
const authMiddleware = require("../Middleware/authorize");
route.post("/login", cntDev.login);
route.get("/count", cntDev.countDev);
route.get("/countadmin", cntDev.countAdmin);
route.use(authMiddleware.verifyToken);
route.get("/viewless", cntDev.viewLess);
route.get("/viewall", cntDev.getDev);
route.post("/addDev", cntDev.addDev);
route.get("/viewbyid/:id", cntDev.getById);
route.delete("/deleteDev/:id", cntDev.delDev);
route.put("/updateDev/:id", cntDev.updateDev);
module.exports = route;
