const { Router } = require("express");
const route = Router();
const cntTask = require("../Controller/task");
route.get("/view", cntTask.viewAll);
route.get("/count", cntTask.countTask);
route.get("/", cntTask.getTask);
route.post("/add", cntTask.addTask);
route.get("/viewbyId/:id", cntTask.getById);
route.delete("/deltask/:id", cntTask.delTask);
route.put("/update/:id", cntTask.updateTask);
// route.get('/task/:did/:id',cntTask.getTaskByUserId);
route.get("/user/:did", cntTask.getAllTaskByUserId);
module.exports = route;
