const { Router } = require("express");
const route = Router();
const cntTask = require("../Controller/task");
route.get("/view", cntTask.viewAll);
route.get("/count", cntTask.countTask);
route.get("/getTask", cntTask.getTask);
route.post("/addTask", cntTask.addTask);
route.get("/viewById/:id", cntTask.getById);
route.delete("/deleteTask/:id", cntTask.delTask);
route.put("/updateTask/:id", cntTask.updateTask);
// route.get('/task/:did/:id',cntTask.getTaskByUserId);
route.get("/user/:did", cntTask.getAllTaskByUserId);
module.exports = route;
